### ISSUE TITLE
recursive directory structure

### ISSUE THREAD

**Issue by bgruening** [bioarchive/aRchive_source_code#15]
See for example this one: https://bioarchive.galaxyproject.org/src/contrib/src/contrib/src/contrib/

**Comment by hexylena** [comment]
yes. Is this a problem for you? As far as I'm concerned this is a non-issue.

**Comment by bgruening** [comment]
Not a problem, but strange.

**Comment by hexylena** [comment]
src/contrib is there to allow for easy package installation for end users. It's recursive because there's no easy way to make it non-recursive without adding a special nginx route and an `ln -s` seemed a lot easier at the time compared to emailing nate and getting him to add a special route for a tiny use case.
