### ISSUE TITLE
Comment: svn versus PACKAGES / built tar balls

### ISSUE THREAD

**Issue by mtmorgan** [bioarchive/aRchive_source_code#36]
More a comment than an issue, and after a very superficial glance so please excuse any misunderstandings.  I would not use svn but rather the public software repository. I'd parse the PACKAGES file at the time point of interest, e.g., (for Bioc version 3.3 at 2016-09-24 09:43:56 EDT)

```
https://bioconductor.org/packages/3.3/bioc/src/contrib/PACKAGES
```

(or the mac / Windows equivalent) and download (rsync) the relevant built (i.e., including processed vignettes and man pages) tar balls.

```
https://bioconductor.org/packages/3.3/bioc/src/contrib/Biobase_2.33.3.tar.gz
```

This would (a) retrieve the publicly available, checked package; (b) include relevant documentation; (c) avoid ambiguity about svn revision / package version; (d) coordinate package versions at time of use; (e) be consistent with use in a normal R installation.

**Comment by hexylena** [comment]
@mtmorgan this project specifically intended to build + maintain all _historical_ versions of packages, every single version that was ever published of each package, rather than just providing a mirror of bioconductor.

We had no interest in hosting the vignettes, nor the man pages because this isn't intended to be used by end users at all, just by the galaxyproject packaging infrastructure (and anyone else who needed historical versions of packages for some reason).

Does this make sense?

**Comment by mtmorgan** [comment]
Yes, historically one is stuck with guessing at the svn / public tar ball relationship. There is no ambiguity going forward (capture the public tarball on a daily basis). This is more than a 'mirror' of Bioconductor, because as various people point out only the current tar ball of each release and the devel branches are retained by Bioconductor for posterity. But I guess if the bioaRchive is updated only periodically rather than e.g., on change of the PACKAGE file then everything is retrospective. Thanks for the clarification.
